MentorEmbedded/meta-sourcery

conf/machine/include/tune-ppce6500.inc

Signed-off-by: Fahad Arslan <Fahad_Arslan@mentor.com>

tune-ppce6500.inc: add e6500 tune files based on oe-core tune file

---

classes/blacklist_dynamic.bbclass
conf/distro/include/tcmode-external-sourcery.inc

Handle our dynamic PNBLACKLIST entries in a generally useful way.

Split out a blacklist_dynamic class

---

recipes-external/glibc/glibc-external.bb
recipes-external/glibc/glibc-external/nscd.conf
recipes-external/glibc/glibc-external/nscd.init
recipes-external/glibc/glibc-external/nscd.service

glibc-external: include nscd startup scripts & .conf

---

recipes-external/gcc/libgfortran-external.bb

libgfortran-external: add recipe

---

recipes-external/gcc/libgcc-external.bb

libgcc-external: dep on binutils, for strip

---

conf/distro/include/tcmode-external-sourcery.inc
core/recipes-devtools/gdb/gdb_%.bbappend

Signed-off-by: Drew Moseley <drew_moseley@mentor.com>

gdb: Conditionally provide gdbserver

---

conf/distro/include/tcmode-external-sourcery.inc
core/recipes-devtools/gdb/gdb_%.bbappend

Fix multiple providers for Jethro branch

---

recipes-external/binutils/binutils-external-cross.bb
recipes-external/gcc/gcc-external-cross.bb

These provides interfered with multi-machine builds.

{gcc,binutils}-external-cross: drop provides of unsuffixed

---

classes/common-license.bbclass
classes/external-toolchain.bbclass
recipes-external/glibc/glibc-sourcery.bb

This is needed to work with the changes coming from Richard soon. See poky's
master-next.

Add missing expand flags

---

recipes-devtools/python/python3_%.bbappend

python3: fix build due to HOST_SYS vs HOST_PREFIX delta

---

classes/external-toolchain.bbclass

gcc-runtime does a do_install_append, now, and was causing failures.

external-toolchain: automatically deal with do_install_append

---

TODO.md
classes/external-toolchain.bbclass

Specifically fixes issues related to the auto provide / skip logic.

Fix a few issues with newer toolchains

---

classes/sanity-external-toolchain.bbclass
conf/distro/include/tcmode-external-sourcery.inc

- Reworked to function the way sanity.bbclass does, rather than running it
every time we do a build
- Add sanity check to test trivial compilation

Revamp the sanity testing

---

conf/distro/include/tcmode-external-sourcery.inc
core/recipes-core/meta/buildtools-tarball.bbappend

Fix issues with buildtools-tarball

---

recipes-external/glibc/glibc-external.bb

glibc-external: libmvec packaging fixes

---

recipes-external/glibc/glibc-sourcery.bb

glibc-sourcery: various fixes from dogwood & cedar updates

---

recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain.bb
recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain/external-codebench-toolchains.sh

sdk-env-external-toolchain: add cb toolchains to the PATH

---

conf/distro/include/tcmode-external-sourcery.inc

tcmode: resolve any CODEBENCH_PATH symlink

---

recipes-sourcery/glibc-sourcery/glibc-sourcery.bb

glibc-sourcery: silence unpackaged /usr/lib warning

---

recipes-sourcery/glibc-sourcery/glibc-sourcery.bb

Reverts MentorEmbedded/meta-sourcery#190

Revert "glibc-sourcery: silence unpackaged /usr/lib warning"

---

conf/layer.conf

layer.conf: add dunfell to compatible series

---

conf/distro/include/tcmode-external-sourcery.inc

tcmode-external-sourcery: also support EXTERNAL_TOOLCHAINS, CODEBENCH_PATH

---

conf/distro/include/tcmode-external-sourcery.inc

tcmode: fix BUILDCFG_VARS typo

---

external-toolchain/recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain.bbappend
external-toolchain/recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain/external-codebench-toolchains.sh

sdk-env-external-toolchain: fix for yocto-based toolchain

---

conf/distro/include/tcmode-external-sourcery.inc

We're moving to this from CODEBENCH_PATH.
JIRA: SB-15621

tcmode: prefer TOOLCHAINS_PATH

---

external-toolchain/recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain.bbappend

sdk-env-external-toolchain: strip off .* from version, not -*

---

external-toolchain/recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain.bbappend

sdk-env-external-toolchain: keep only the first 2 dot-separated components

---

recipes-core/packagegroups/packagegroup-core-sdk.bbappend

These are not currently provided by our toolchains.
JIRA: SB-16099

packagegroup-core-sdk: remove sanitizers

---

conf/distro/include/tcmode-external-sourcery.inc

tcmode: use SALT_LICENSE_SERVER for newer toolchains

---

conf/distro/include/tcmode-external-sourcery.inc

tcmode: add do_kernel_configme to network tasks
