MentorEmbedded/meta-sourcery

- conf/distro/include/tcmode-external-sourcery.inc
This is more a distro/user decision, I think, so move it there. Also this was
insufficient, as just removing `packagegroup-cross-canadian-${MACHINE}` without
adding back in `meta-environment-${MACHINE}` results in an sdk which hangs on
install.
See https://github.com/MentorEmbedded/meta-mentor/pull/414 for the improved
version of this in our distro layer.
> tcmode: drop sdk toolchain removal

- conf/distro/include/external-run.inc
TMPDIR is already in the BB_HASHBASE_WHITELIST, whereas TOPDIR is not.
> external-run.inc: run in TMPDIR, not TOPDIR

- classes/external-toolchain.bbclass
- classes/package_qa_sourcery.bbclass
- core/recipes-core/ncurses/ncurses_%.bbappend
Since we're running cp -p to preserve other aspects, we need to manually
correct the ownership to what we expect (root:root) rather than the current
ownership.
> Correct file ownership and add ownership QA test

- classes/external-toolchain.bbclass
- recipes-external/glibc/glibc-external.bb
It was hardcoding the path, which caused problems depending on the multilib
setup in question (e.g. for mx6). Now it uses the usual sysroot search methods
to find it.
> glibc-external: fix issue locating errno.h

- classes/package_qa_sourcery.bbclass
This fixes a failure to execute bitbake-worker to execute this task.
> package_qa_sourcery: fix fakeroot handling

- recipes-external/glibc/glibc-sysroot-setup.inc
This was causing it to package the entire sysroot in certain cases.
> glibc: don't install a multilib suffix of '.'

- recipes-external/glibc/glibc-external.bb
This ensures that we get a pleasant error message when EXTERNAL_TOOLCHAIN is
unset, rather than getting tracebacks.
> glibc-external: fix fallback for license/pv

- conf/distro/include/tcmode-external-sourcery.inc
This fixes issues with multilib handling.
JIRA: SB-4705
> Properly blacklist ${TARGET_ARCH}-suffixed recipes

- conf/distro/include/sourcery-tuning.inc
The most common failure case was qemuarm.
Upstream binutils doesn't support -march=armv5e, even though gcc does. oe-core
is carrying a patch to add it, but Sourcery G++ does not do so. Currently,
ARMPKGSFX_THUMB is used in TUNE_CCARGS, and it only includes 't' when
ARM_INSTRUCTION_SET=thumb. Bypass that check for armv5, as we need
-march=armv5te rather than -march=armv5e, but we still want -mthumb removed
when appropriate.
Fixes #86
> sourcery-tuning: fix -march=armv5e failures

- classes/external-toolchain.bbclass
This improves the error message when we can't build one of our recipes due to it being skipped, due to not finding any of its files in the external toolchain, by removing all the unnecessary .debug dirs in that context.
> external-toolchain: filter out .debug for parse time check

- core/recipes-core/glibc/glibc-locale_%.bbappend
- recipes-external/gcc/gcc-runtime-external.bb
- recipes-external/gcc/libgcc-external.bb
- recipes-external/glibc/glibc-external.bb
- Fixes build-deps warnings due to the interdependency between glibc & libgcc (libgcc requires libc6, but glibc's utilities require libgcc)
- Fixes build-deps warnings due to locale-base subpackages depending on non-existent glibc-binary-localedata subpackages due to naming mismatches (e.g. 'utf8' externally, expected to be 'utf-8' by glibc-locale
- Fixed support for use of pre-compiled locales while I was at it, as a useful test case
Fixes #81
> Fix various warning/QA issues

- recipes-external/glibc/glibc-external.bb
We were seeing an error message about bits/syscall.h being missing. Fix by
removing the bits/syscall.h setup from the glibc-package do_install_append.
Thanks to @arehman199   for finding the root cause of this problem.
> glibc-external: don't setup bits/syscall.h

- conf/distro/include/tcmode-external-sourcery.inc
We were explicitly removing the old default install path. Rather than
explicitly removing the new install path, remove */codebench/bin/, since
that's the new structure of the installs.
JIRA: SB-5383
> tcmode: improve CodeBench PATH removal

- conf/distro/include/tcmode-external-sourcery.inc
- recipes-external/glibc/glibc-external.bb
- recipes-external/glibc/glibc-sysroot-setup.inc
- recipes-sdk/external-script/external-script/external.sh
- recipes-sdk/external-script/nativesdk-external-script.bb
With this, we can avoid the need to create a symlink for the multilib sysroot
suffix. This also adds a nativesdk package to the sdk to adjust the
environment setup there to use it as well.
JIRA: SB-6018
> Use --no-sysroot-suffix

- conf/distro/include/tcmode-external-sourcery.inc
> tcmode: add aarch64 to EXTERNAL_TARGET_SYSTEMS

- conf/distro/include/tcmode-external-sourcery.inc
The library path in the sourcery toolchain for aarch64 is lib64, not lib.
> tcmode: fix BASELIB for aarch64

- conf/distro/include/tcmode-external-sourcery.inc
This reverts commit 4c72f28c6ecc691bcd7f04ac5fddccb2f2a6998b
to align localedir with the external toolchain
Signed-off-by: Abdur Rehman <abdur_rehman@mentor.com>
> tcmode: set localedir back to ${exec_prefix}/lib/locale

- conf/distro/include/tcmode-external-sourcery.inc
When ${EXTERNAL_TOOLCHAIN}/bin doesn't exist, it prints:
ERROR: EXTERNAL_TOOLCHAIN is invalid: path '/scratch/cedar/toolchains/arm/bin/bin' does not exist
> Improve external toolchain sanity checks

- recipes-external/gcc/libgcc-external.bb
This aligns with the non-external recipe, and as ${PN}-dev already disables
the staticdev QA check, this also silences the libgcov-dev QA warning. We
could also have changed libgcov-dev to ${MLPREFIX}libgcov-dev.
JIRA: SB-6225
> libgcc-external: move libgcov.a to ${PN}-dev

- recipes-external/gcc/libgfortran-external.bb
There's no need to override this, the default packages is fine, and we already
rprovides the non-external-suffixed package names. This would also have caused
breakage for multilib builds, as the specified package names in PACKAGES
didn't include MLPREFIX.
> libgfortran-external: kill unneeded and wrong PACKAGES

- conf/distro/include/sourcery-tuning.inc
Remove -mcpu=e6500 flag from TUNE_CCARGS for t4240rdb-64b
to match the toolchain options, in ADE's environment script,
with the CS3 data used by the IDE(Sourcery CodeBench).
IDE reads in the individual ABI and other toolchain options
from ADE's environment-setup script and attempts to map each
value to its appropriate OptionValue in the target data
plugin.xml. Many of the the values in the plugin.xml
(particularly the ABI values) originate from the CS3
information.
When the IDE finds a value in environment-setup script which
cannot be mapped to a value in plugin.xml, e.g -mcpu=e6500 in
this case, it simply appends it to the misc option field and
this behavior is known to be imperfect.
JIRA: SB-6290
Signed-off-by: Abdur Rehman <abdur_rehman@mentor.com>
> sourcery-tuning: remove -mcpu flag for t4240rdb-64b

- conf/distro/include/tcmode-external-sourcery.inc
- core/recipes-devtools/gdb/gdb_%.bbappend
@Noor-Ahsan this is identical to what is in the master branch.  I'm requesting this against the cedar branch since the AMD platforms need the ability to build target tools.  Per our discussion this morning I think the right approach is to merge this into the cedar branch for the async and let the locked down manifest for the formal Cedar release keep the old commit hash.  Is that right?
> Fix multiple providers for cedar asyncs

- conf/distro/include/tcmode-external-sourcery.inc
The Sourcery x86-64 toolchain leaves 'lib' empty and uses 'lib64' for
everything, so force that in the tcmode the way we do for aarch64.
This also switches from hardcoding BASELIB to using the bits defined in the
tuning files, to reduce how much is being hardcoded.
Thanks to @skrishnakar for finding this one. meta-sourcery fails to find libc.so
for qemux86-64 without this.
> tcmode: also override baselib for x86-64

- conf/distro/include/tcmode-external-sourcery.inc
Work around failure in 'perf' due to use of ld rather than gcc to link.
JIRA: SB-6527
> tcmode: define LDEMULATION_x86-64

- recipes-sdk/external-script/nativesdk-external-script.bb
This is a script -- we don't want to suck in the toolchain. I thought about
also pulling in allarch, but I don't know how that interacts with nativesdk
yet.
> nativesdk-external-script: set INHIBIT_DEFAULT_DEPS

- conf/distro/include/tcmode-external-sourcery.inc
We get build failures otherwise.
> Set BASELIB rather than baselib

- conf/distro/include/tcmode-external-sourcery.inc
This can fix a failure to pick up the needed argument for our flags.
> Pass *_LICENSE_FILE to gcc in msgxx-glibc test

- conf/distro/include/tcmode-external-sourcery.inc
Old messages:
WARNING: EXTERNAL_TARGET_SYS == TARGET_SYS. This indicates that the prefixes specified by EXTERNAL_TARGET_SYSTEMS were not found.
ERROR: EXTERNAL_TOOLCHAIN gcc path '<external-toolchain>/bin/arm-mel-linux-gnueabi-gcc' does not exist
New message:
ERROR: Unable to locate prefixed gcc binary for arm-mel-linux-gnueabi in <external-toolchain>/bin
> Improve the error for missing gcc binary

- conf/distro/include/tcmode-external-sourcery.inc
There's no reason not to make use of it, and it's used by default with the
internal toolchain, so this aligns us closer to that.
> tcmode: use -Wl,--as-needed

- classes/external-toolchain.bbclass
- lib/oe/external.py
- recipes-external/gcc/gcc-runtime-external.bb
oe.path.check_output was returning a bytes, not an str. Switch to bb.process
to resolve issues with python3.
> Updates for python 3

- recipes-external/glibc/glibc-external.bb
libssp_nonshared.a is installed by gcc-runtime-external so
glibc-external should not install this into a shared area when
it already exists.
Signed-off-by: Fahad Arslan <Fahad_Arslan@mentor.com>
> glibc-external: don't install already installed libssp_nonshared.a

- classes/codebench.bbclass
- conf/distro/include/tcmode-external-sourcery.inc
If the user hasn't set EXTERNAL_TOOLCHAIN, but CODEBENCH_PATH is set, then we automatically set both EXTERNAL_TOOLCHAIN and EXTERNAL_TARGET_SYS based on the installed toolchains in CODEBENCH_PATH/../toolchains.
> Add bits to handle the new codebench layout

- README.md
- core/recipes-connectivity/ppp/ppp_2.4.7.bbappend
A patch in oe-core is needed, at this time, to fix builds with
linux-libc-headers from the 4.8 Linux kernel or newer, which is not the case
for most external toolchains. Unfortunately, this patch also breaks the build
of ppp with older linux-libc-headers, so we need to revert it. A note in the
README is added explaining how to disable this for external toolchains with
recent enough kernel libc headers.
> Fix builds of the ppp recipe with most toolchains

- conf/distro/include/tcmode-external-sourcery.inc
Per @Noor-Ahsan, drop old unsupported lite toolchain triplets.
JIRA: SB-8226
> tcmode: drop old triplets/prefixes

- classes/external-common.bbclass
- core/recipes-connectivity/ppp/ppp_2.4.7.bbappend
Since the external toolchain is available at parse time, we can actually grab
the kernel version from the external toolchain sysroot and use that to
determine whether to apply the patch. Do so.
> ppp: obey the actual libc kernel version

- xilinx-mel/recipes-core/packagegroups/packagegroup-core-standalone-sdk-target.bbappend
Sourcery codebench toolchain for aarch64 architecture doesn't have
libatomic available which causes ade build failure. Drop the
dependency on libatomic for aarch64 based xilinx MPSoC target.
JiraID: ITS-50
Signed-off-by: Yasir-Khan <yasir_khan@mentor.com>
> xilinx: aarch64: drop dependency on libatomic

- conf/distro/include/tcmode-external-sourcery.inc
Signed-off-by: Christopher Larson chris_larson@mentor.com
> tcmode: disable 32-bit pseudo for 64-bit codebench

- lib/oe/external.py
If we run in tmpdir, and run a bitbake -e after wiping tmpdir,
EXTERNAL_TOOLCHAIN_SYSROOT will be 'UNKNOWN' rather than the correct path, due
to PWD not existing when we try to extract the sysroot path.
> oe.external: run in topdir, not tmpdir

- conf/distro/include/tcmode-external-sourcery.inc
It's not ideal to do this for every build, but it's not terrible, either, and
is worth the cost to get an error up front if there's a configuration or
licensing problem. master deals with this more cleanly. The previous behavior
was particularly troublesome, as it'd fail to extract the sysroot, which would
result in the external toolchain recipes skipping themselves, and the user not
getting a useful error at all.
JIRA: SB-8257
> tcmode: add compilation toolchain sanity test

- recipes-devtools/perl/perl_%.bbappend
libssp support is only available in toolchain for minnowmax so
remove it until there is a requirement.
Jira ID: SB-8337
Signed-off-by: Fahad Arslan <Fahad_Arslan@mentor.com>
> perl-ptest: remove runtime dep on libssp

- classes/sanity-external-toolchain.bbclass
If the EXTERNAL_TOOLCHAIN path doesn't exist, the error logic had a variable
name issue (extdir vs extpath). Fix.
> sanity-external-toolchain: fix variable name

- classes/external-toolchain-cross.bbclass
- classes/sanity-external-toolchain.bbclass
- conf/distro/include/tcmode-external-sourcery.inc
Since the external-cross recipes link/wrap the binaries already, there's no
actual need to override TARGET_PREFIX anymore.
> Drop the change of TARGET_PREFIX

- classes/external-toolchain.bbclass
- recipes-external/gcc/gcc-runtime-external.bb
- recipes-external/gcc/libgcc-external.bb
- Disable the debug split
- Gather up the .debug files corresponding to the FILES
JIRA: SB-8524
> Correctly include existing debug files from the toolchain

- conf/distro/include/sourcery-tuning.inc
-a64 and -me6500 are PowerPC architecture-specific assembler flags
only intended for 64bit mode of e6500 core.
-a64 - generates ELF64 or XCOFF64.
-me6500 - generates code for Freescale e6500 core complex.
Jira ID: http://jira.alm.mentorg.com:8080/browse/SIEJIR-3452
Signed-off-by: Fahad Arslan <Fahad_Arslan@mentor.com>
> sourcery-tuning.inc: make assembler flags e6500-64b specific

- conf/distro/include/tcmode-external-sourcery.inc
This makes it clear that this refers to the toolchain, not the CodeBench IDE.
JIRA: SB-8699
> tcmode: use SOURCERY_TOOLCHAIN_VERSION for the build cfg summary

- recipes-external/gcc/gcc-runtime-external.bb
We don't need or want this dep, so set it to the empty string rather than
including gcc-common.inc. This fixes builds with current upstream master.
> gcc-runtime-external: fix COMPILERDEP parse error

- recipes-bsp/systemd-boot/systemd-boot_232.bbappend
Ensure -m32/-m64 are passed for EFI, as the buildsystem currently relies on
the default for the toolchain, which isn't necessarily correct for an external
toolchain.
> systemd-boot: fix build issue on x86_64

- recipes-external/glibc/glibc-sourcery.bbappend
Add bbappend file parallel to the recipe file because the glibc-sourcery
recipe from updates layer is being used and that layer is locked right now.
It fixes the following QA warning;
WARNING: glibc-sourcery-2.24-2016.11-66-r0 do_package_qa: QA Issue:
/etc/init.d/nscd contained in package nscd requires /bin/bash, but no
providers found in RDEPENDS_nscd? [file-rdeps]
Jira: http://jira.alm.mentorg.com:8080/browse/SB-9978
Signed-off-by: Fahad Usman <fahad_usman@mentor.com>
> glibc-sourcery: Avoid dependency of bash

- recipes-external/glibc/glibc-external.bbappend
- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
Silence any errors from oe_multilib_header, as we don't care about missing
multilib headers, as the oe-core glibc version isn't necessarily the same as
our own.
> glibc-{external,sourcery}: silence all oe_multilib_header errors

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
oe_filter_out no longer exists upstream, and was deprecated for some time.
> glibc-sourcery: use oe.utils.str_filter_out, not oe_filter_out

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
These were obsolete bits removed from the glibc recipe in oe-core, and
are provided by other recipes.
> glibc-sourcery: drop nsl/rpc bits

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
This recipe isn't external, it builds glibc, so we need to set LICENSE
correctly for glibc. CLOSED is not correct.
JIRA: SB-11852
> glibc-sourcery: fix LICENSE

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
We can remove it in do_install rather than do_package, the reason it was
failing before is it contained an empty locale subdir from the locale
processing. If we remove that as well, it works.
JIRA: SB-11811
> glibc-sourcery: silence unpackaged /usr/lib warning

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
After the stash step the cleanups are done in post_stash_cleanup
so it is more appropriate to append the corresponding function.
Additionally a patch has been submitted upstream to fix the
actual bug in libc-common.
https://patchwork.openembedded.org/patch/154968/
So once this starts failing here we should drop the function
append.
Signed-off-by: Awais Belal <awais_belal@mentor.com>
> glibc-sourcery: move /usr/lib cleanup to post_stash_cleanup

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
We already remove the bash shebang from the scripts that had unnecessary
usage of bash, so this isn't needed.
> glibc-sourcery: drop unnecessary bash rdep

- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
This requires the corresponding workaround in meta-external-toolchain to
avoid a recursion with gcc-runtime.
JIRA: SB-12465
> glibc: fix warnings about libssp for builds with security flags

- recipes-external/linux-libc-headers/linux-libc-headers-external.bb
> linux-libc-headers-external: skip multilib header processing

- conf/distro/include/tcmode-external-sourcery-rebuild-libc.inc
libxcrypt provides crypt now, and we can't build something that's blacklisted.
> tcmode: fix external-sourcery-rebuild-libc

- conf/distro/include/tcmode-external-sourcery-rebuild-libc.inc
- recipes-core/glibc/glibc_%.bbappend
- glibc: also kill linux libc headers here for rebuild-libc
- tcmode: fix external-sourcery-rebuild-libc
> Fix rebuild libc

- conf/distro/include/tcmode-external-sourcery.inc
> tcmode: fix exception when SETUP_SCRIPT var is set

- conf/distro/include/tcmode-external-sourcery.inc
- recipes-core/glibc/glibc_%.bbappend
- tcmode: handle $scriptdir in sysroot paths
- glibc: only apply to class-target
> Fix for nativesdk-libgcc and $scriptdir

- conf/distro/include/tcmode-external-sourcery.inc
> tcmode-external-sourcery: resolve CODEBENCH_PATH to fix use with the installer

- external-toolchain/recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain.bbappend
This was looking in the TUNE_PKGARCH path, but needed to look in the TARGET_ARCH path.
JIRA: SB-15747
> sdk-env-external-toolchain: correct sys

- external-toolchain/recipes-sdk/sdk-env-external-toolchain/sdk-env-external-toolchain.bbappend
> sdk-env-external-toolchain: correct escaping for dirsuffix

- recipes-core/glibc/glibc_%.bbappend
The do_configure step fails with
tmp/work/aarch64-mel-linux/glibc/2.31+gitAUTOINC+6fdf971c9d-r0/temp/run.do_configure.24059: Bad substitution
WARNING: exit code 2 from a shell command.
This happens because of an unexpanded PKGVERSION which fails
to find SOURCERY_VERSION that is only set with toolchain's
external mode. Even defining a default for this variable
would be wrong as external_run() returns UNKNOWN for tcmode
not starting with external so get_pkgversion() does not return
anything or more appropriately None in this case. For yocto
internal toolchain defining a default for SOURCERY_VERSION
would pass a wrong pkgversion (SOURCERY_NAME SOURCERY_VERSION)
on to configure due to this.
We now conditionalize the appending of pkgverion and bug report
url so it is only done for external …
> [dunfell] glibc: only append pkgversion and bug report url for Sourcery

- recipes-external/gcc/gcc-runtime-external.bbappend
- recipes-external/glibc/glibc-external.bbappend
- recipes-sourcery/glibc-sourcery/glibc-sourcery.bb
CUSTOMER ISSUE ID: TBD
MGC ISSUE ID: OPP-713, SB-15901, ADIT-75
SUMMARY: Setup a full ADIT build tree with rebuilding glibc based on CB 11
DESCRIPTION: Setup a full ADIT build tree with rebuilding glibc based on CB 11
RESOLUTION: Backport upstream fixes.
DEPENDENCIES: https://stash.alm.mentorg.com/projects/ADITGEN4/repos/adit-gen4-manifests/pull-requests/30/overview (adds branch cos10-adit to the manifest)
LICENSE: MIT
TEST SUMMARY: Build test with TCMODE = "external-sourcery" (current COS default) and with TCMODE = "external-sourcery-rebuild-libc" (we will use it for CVE fixes in glibc) in local.conf.
KNOWN LIMITATIONS: None
SOURCES: None
> Fix warnings about libssp for builds with security flags

- recipes-external/glibc/glibc-external.bbappend
- recipes-external/linux-libc-headers/linux-libc-headers-external.bb
JIRA: SB-20035
These fixes are needed to use the meta-sourcery `TCMODE` with a Yocto 4.0 based CodeBench toolchain.
> Fix header conflicts between glibc and linux-libc-headers

- conf/distro/include/tcmode-external-sourcery.inc
- core/recipes-core/meta/meta-environment.bbappend
- recipes-core/packagegroups/packagegroup-cross-canadian.bbappend
- recipes-external/external-toolchain/external-toolchain.bb
JIRA: SB-19962
This has one major remaining issue to address in the future, and one area worth investigation:
- `LICENSE` isn't correct in `external-toolchain`, but we want this to match the contents of the packaged external toolchain, so we need that information to be available in the CodeBench toolchain and pull it from there. We could potentially package and include -lic packages in the sysroots, or we could add common license files for all licenses in question to the legal directory, etc.
- We should consider attempting to construct the Yocto SDK on top of the existing CodeBench toolchain Yocto SDK, rather than embedding one in the other.
> Ship the external toolchain in the Yocto SDK

- conf/distro/include/tcmode-external-sourcery.inc
By default, oe-core disables network access in all but the fetch tasks
to improve reproducibility, as we don't want recipes fetching things for
their builds, but we need network access retained for license server
access for the toolchain, so re-enable it for the configure/compile
tasks.
JIRA: SB-20919
> tcmode: enable network in compile tasks for license server access

- recipes-external/external-toolchain/external-toolchain.bb
This stuff has already been built and processed, there's no point doing
it ourselves, and can result in build failures due to missing objcopy.
> external-toolchain: skip strip and debug split

- classes/sdk-relocate-toolchain.bbclass
- conf/distro/include/tcmode-external-sourcery.inc
As we're redistributing the toolchain in our SDK, rather than building upon it, we're nesting Yocto SDKs. We need to ensure that both of them are relocated to the correct install path after installation.
JIRA: SB-20930
> Re-relocate a distributed toolchain when relocating our SDK

- classes/sdk-relocate-toolchain.bbclass
Rather than relying on toolchain-shar-relocate.sh having a trailing
newline to separate the content, ensure we have one here for safety.
With the current behavior, if toolchain-shar-relocate.sh lacks a trailing
newline at the end of the file, this will be directly concatenated to that, so
the first line of this function and the last of that file will be merged to a
single line, resulting in failures.
JIRA: SB-21318
> sdk-relocate-toolchain.bbclass: add a preceding newline to be safe

- recipes-external/external-toolchain/external-toolchain.bb
- Add the readme in SRC_URI to ensure it gets picked up by any source
archival methods, such as archiver.
- Add the readme as a license file to be included by tasks such as
do_populate_lic, which ensures it is present in tmp/deploy/licenses.
JIRA: SB-20379, SB-20380
With this, we see the following in tmp/deploy/licenses when building an image or the recipe directly:
```console
$ ls tmp/deploy/licenses/external-toolchain-aarch64
generic_Sourcery-Toolchain  ReadMe_OSS.html  recipeinfo
```
And with archiver enabled with `ARCHIVER_MODE[src]="original"` and `COPYLEFT_LICENSE_INCLUDE="*"`:
```console
$ ls tmp/deploy/sources/aarch64-oe-linux/external-toolchain-aarch64-1.0-r0
ReadMe_OSS.html
```
> external-toolchain: pull in the ReadMe_OSS.html file when present 

- conf/distro/include/tcmode-external-sourcery.inc
Re-export the variables and exclude them from checksums.
JIRA: CB-17681
> tcmode: also handle other SALT licensing variables

- recipes-core/packagegroups/packagegroup-cross-canadian.bbappend
As the external toolchain is a cross-canadian recipe just like
gcc/binutils/gdb, we need to duplicate the logic used for the latter
with the former, to ensure that all toolchains needed for all multilib
configurations are also redistributed with the SDK.
JIRA: SB-22039, SB-22040
> packagegroup-cross-canadian: install toolchains for all multilibs

- classes/sdk-relocate-toolchain.bbclass
We need to ensure that relocate_sdk.sh is run for the toolchain included for each multilib, not only the base configuration.
JIRA: SB-22039, SB-22040
> sdk-relocate-toolchain.bbclass: relocate toolchains for all multilibs
